const states = {
  alabama: "al",
  kentucky: "ky",
  ohio: "oh",
  alaska: "ak",
  louisiana: "la",
  oklahoma: "ok",
  arizona: "az",
  Maine: "me",
  oregon: "or",
  arkansas: "ar",
  maryland: "md",
  pennsylvania: "pa",
  americansamoa: "as",
  massachusetts: "ma",
  puertorico: "pr",
  california: "ca",
  michigan: "mi",
  rhodeisland: "ri",
  colorado: "co",
  minnesota: "mn",
  southcarolina: "sc",
  connecticut: "ci",
  mississippi: "ms",
  southdakota: "sd",
  delaware: "de",
  missouri: "mo",
  tennessee: "tn",
  districtofcolumbia: "dc",
  montana: "mt",
  texas: "tx",
  florida: "fl",
  nebraska: "ne",
  trustterritories: "tt",
  georgia: "ga",
  nevada: "nv",
  guam: "gu",
  newhampshire: "nh",
  vermont: "vt",
  hawaii: "hi",
  newjersey: "nj",
  virginia: "va",
  idaho: "id",
  newmexico: "nm",
  virginislands: "vi",
  ohio: "oh",
  ohio: "oh",
  ohio: "oh",
  ohio: "oh",
  ohio: "oh",
  ohio: "oh",
  ohio: "oh",
  ohio: "oh",
  ohio: "oh",
};

module.exports = states;

/*Illinois	IL	New York	NY	Washington	WA
Indiana	IN	North Carolina	NC	West Virginia	WV
Iowa	IA	North Dakota	ND	Wisconsin	WI
Kansas	KS	Northern Mariana Islands	MP	Wyoming	WY */
