const states = {
  alabama: "al",
  kentucky: "ky",
  ohio: "oh",
  alaska: "ak",
  louisiana: "la",
  oklahoma: "ok",
  arizona: "az",
  Maine: "me",
  oregon: "or",
  arkansas: "ar",
  maryland: "md",
  pennsylvania: "pa",
  americansamoa: "as",
  massachusetts: "ma",
  puertorico: "pr",
  california: "ca",
  michigan: "mi",
  rhodeisland: "ri",
  colorado: "co",
  minnesota: "mn",
  southcarolina: "sc",
  connecticut: "ci",
  mississippi: "ms",
  southdakota: "sd",
  delaware: "de",
  missouri: "mo",
  tennessee: "tn",
  districtofcolumbia: "dc",
  montana: "mt",
  texas: "tx",
  florida: "fl",
  nebraska: "ne",
  trustterritories: "tt",
  georgia: "ga",
  nevada: "nv",
  guam: "gu",
  newhampshire: "nh",
  vermont: "vt",
  hawaii: "hi",
  newjersey: "nj",
  virginia: "va",
  idaho: "id",
  newmexico: "nm",
  virginislands: "vi",
  illinois: "il",
  newyork: "ny",
  washington: "wa",
  indiana: "in",
  northcarolina: "NC",
  westvirginia: "WV",
  iowa: "IA",
  northdakota: "nd",
  wisconsin: "wi",
  ohio: "oh",
  ohio: "oh",
  ohio: "oh",
  ohio: "oh",
};

module.exports = states;

/*	Kansas	KS	Northern Mariana Islands	MP	Wyoming	WY */
